export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const FETCH_HIGHSCORES = 'FETCH_HIGHSCORES';
export const FETCH_HIGHSCORES_START = 'FETCH_HIGHSCORES_START';
export const FETCH_HIGHSCORES_SUCCESS = 'FETCH_HIGHSCORES_SUCCESS';
export const FETCH_HIGHSCORES_FAIL = 'FETCH_HIGHSCORES_FAIL';

export const ADD_HIGHSCORE = 'ADD_HIGHSCORE';
export const ADD_HIGHSCORE_START = 'ADD_HIGHSCORE_START';
export const ADD_HIGHSCORE_SUCCESS = 'ADD_HIGHSCORE_SUCCESS';
export const ADD_HIGHSCORE_FAIL = 'ADD_HIGHSCORE_FAIL';
